[package]
name = "shuuro-wasm"
version = "0.1.7"
authors = ["uros-5"]
edition = "2021"
description = "Library for shuuro-wasm on client part."
repository = "https://github.com/uros-5/shuuro-wasm"
license = "Apache-2.0 license"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = {version = "0.2.84", features = ["serde-serialize"]}
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.61"
shuuro = {git = "https://github.com/uros-5/shuuro", branch = "extended", features = ["shuuro12"]}
getrandom = { version = "0.2.8", features = ["js"] }
serde-wasm-bindgen = "0.4"
#shuuro deps
itertools = "0.10"
bitintr = "0.3"
thiserror = "1.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }
dlmalloc = "0.2.4"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
